"""Initial migration based on current models

Revision ID:  
Revises: 
Create Date: 2025-04-07 11:00:57.266279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '030c789dd8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_groups', sa.Column('active_penalty_text', sa.String(length=255), nullable=True))
    op.drop_index('ix_shared_challenges_creator_user_id', table_name='shared_challenges')
    op.create_index(op.f('ix_shared_challenges_creator_id'), 'shared_challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_shared_challenges_id'), 'shared_challenges', ['id'], unique=False)
    op.drop_constraint('shared_challenges_ibfk_1', 'shared_challenges', type_='foreignkey')
    op.drop_column('shared_challenges', 'creator_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_challenges', sa.Column('creator_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shared_challenges_ibfk_1', 'shared_challenges', 'users', ['creator_user_id'], ['id'])
    op.drop_index(op.f('ix_shared_challenges_id'), table_name='shared_challenges')
    op.drop_index(op.f('ix_shared_challenges_creator_id'), table_name='shared_challenges')
    op.create_index('ix_shared_challenges_creator_user_id', 'shared_challenges', ['creator_user_id'], unique=False)
    op.drop_column('challenge_groups', 'active_penalty_text')
    # ### end Alembic commands ###
