"""add_current_game_to_challenge_group

Revision ID: 036d5c73a888
Revises: 4d23d9a00603
Create Date: 2025-05-26 15:30:21.183606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036d5c73a888'
down_revision = '4d23d9a00603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_game_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.drop_column('current_game_info')

    # ### end Alembic commands ###
