"""empty message

Revision ID: 3a0db54159c4
Revises: 030c789dd8c2
Create Date: 2025-04-07 11:05:08.842465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a0db54159c4'
down_revision = '030c789dd8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - START ###

    # Add the new column (fine to do this early)
    op.add_column('challenge_groups', sa.Column('active_penalty_text', sa.String(length=255), nullable=True))

    # --- CORRECTED ORDER for shared_challenges cleanup ---
    # 1. Drop the constraint that uses the column/index
    op.drop_constraint('shared_challenges_ibfk_1', 'shared_challenges', type_='foreignkey')
    # 2. Drop the index associated with the old column
    op.drop_index('ix_shared_challenges_creator_user_id', table_name='shared_challenges')
    # 3. Drop the old column itself
    op.drop_column('shared_challenges', 'creator_user_id')
    # --- END CORRECTED ORDER ---

    # Create the new indexes (fine to do this after cleanup)
    op.create_index(op.f('ix_shared_challenges_creator_id'), 'shared_challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_shared_challenges_id'), 'shared_challenges', ['id'], unique=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - START ###

    # --- CORRECTED ORDER for downgrade ---
    # 1. Add the old column back
    op.add_column('shared_challenges', sa.Column('creator_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # 2. Add the old index back
    op.create_index('ix_shared_challenges_creator_user_id', 'shared_challenges', ['creator_user_id'], unique=False)
    # 3. Add the old constraint back
    op.create_foreign_key('shared_challenges_ibfk_1', 'shared_challenges', 'users', ['creator_user_id'], ['id'])
    # --- END CORRECTED ORDER ---

    # Drop the new indexes
    op.drop_index(op.f('ix_shared_challenges_id'), table_name='shared_challenges')
    op.drop_index(op.f('ix_shared_challenges_creator_id'), table_name='shared_challenges')

    # Drop the new column
    op.drop_column('challenge_groups', 'active_penalty_text')

    # ### end Alembic commands ###
