"""Initial migration.

Revision ID: 465cf388d581
Revises: 
Create Date: 2025-04-13 12:32:36.437509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465cf388d581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Spiel', sa.String(length=100), nullable=False),
    sa.Column('Spielmodus', sa.String(length=100), nullable=False),
    sa.Column('Schwierigkeit', sa.Float(), nullable=False),
    sa.Column('Spieleranzahl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_entries_Spiel'), 'game_entries', ['Spiel'], unique=False)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('saved_game_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_tab_id', sa.String(length=100), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('entries_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_game_tabs_client_tab_id'), 'saved_game_tabs', ['client_tab_id'], unique=False)
    op.create_index(op.f('ix_saved_game_tabs_user_id'), 'saved_game_tabs', ['user_id'], unique=False)
    op.create_table('saved_penalty_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_tab_id', sa.String(length=100), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('penalties_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_penalty_tabs_client_tab_id'), 'saved_penalty_tabs', ['client_tab_id'], unique=False)
    op.create_index(op.f('ix_saved_penalty_tabs_user_id'), 'saved_penalty_tabs', ['user_id'], unique=False)
    op.create_table('shared_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('challenge_data', sa.JSON(), nullable=False),
    sa.Column('penalty_info', sa.JSON(), nullable=True),
    sa.Column('max_groups', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_players_per_group', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_challenges_creator_id'), 'shared_challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_shared_challenges_id'), 'shared_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_shared_challenges_public_id'), 'shared_challenges', ['public_id'], unique=True)
    op.create_table('challenge_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_challenge_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_penalty_text', sa.String(length=255), nullable=True),
    sa.Column('player_names', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['shared_challenge_id'], ['shared_challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_groups_id'), 'challenge_groups', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_groups_shared_challenge_id'), 'challenge_groups', ['shared_challenge_id'], unique=False)
    op.create_index('uq_shared_challenge_group_name', 'challenge_groups', ['shared_challenge_id', 'group_name'], unique=True)
    op.create_table('user_challenge_group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['challenge_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_challenge_group_membership')
    op.drop_index('uq_shared_challenge_group_name', table_name='challenge_groups')
    op.drop_index(op.f('ix_challenge_groups_shared_challenge_id'), table_name='challenge_groups')
    op.drop_index(op.f('ix_challenge_groups_id'), table_name='challenge_groups')
    op.drop_table('challenge_groups')
    op.drop_index(op.f('ix_shared_challenges_public_id'), table_name='shared_challenges')
    op.drop_index(op.f('ix_shared_challenges_id'), table_name='shared_challenges')
    op.drop_index(op.f('ix_shared_challenges_creator_id'), table_name='shared_challenges')
    op.drop_table('shared_challenges')
    op.drop_index(op.f('ix_saved_penalty_tabs_user_id'), table_name='saved_penalty_tabs')
    op.drop_index(op.f('ix_saved_penalty_tabs_client_tab_id'), table_name='saved_penalty_tabs')
    op.drop_table('saved_penalty_tabs')
    op.drop_index(op.f('ix_saved_game_tabs_user_id'), table_name='saved_game_tabs')
    op.drop_index(op.f('ix_saved_game_tabs_client_tab_id'), table_name='saved_game_tabs')
    op.drop_table('saved_game_tabs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_game_entries_Spiel'), table_name='game_entries')
    op.drop_table('game_entries')
    # ### end Alembic commands ###
