"""add_tagging_system

Revision ID: 4d23d9a00603
Revises: 62fc16c414c7
Create Date: 2025-05-26 15:26:36.083046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d23d9a00603'
down_revision = '62fc16c414c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('game_tags',
    sa.Column('game_entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_entry_id'], ['game_entries.id'], name='fk_game_tags_game_entry_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_game_tags_tag_id'),
    sa.PrimaryKeyConstraint('game_entry_id', 'tag_id')
    )
    op.create_table('penalty_tags',
    sa.Column('penalty_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalties.id'], name='fk_penalty_tags_penalty_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_penalty_tags_tag_id'),
    sa.PrimaryKeyConstraint('penalty_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalty_tags')
    op.drop_table('game_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    # ### end Alembic commands ###
