"""add is_custom_built to sharedchallenge

Revision ID: 62fc16c414c7
Revises: d8cfaaf32bc9
Create Date: 2025-05-22 17:42:35.742639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fc16c414c7'
down_revision = 'd8cfaaf32bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'sqlite':
        with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_custom_built', sa.Boolean(), nullable=True))
        op.execute('UPDATE shared_challenges SET is_custom_built = FALSE WHERE is_custom_built IS NULL')
        with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
            batch_op.alter_column('is_custom_built', existing_type=sa.Boolean(), nullable=False, server_default=sa.false())
    else:
        with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_custom_built', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
        batch_op.drop_column('is_custom_built')

    # ### end Alembic commands ###
