"""add_penalty_duration_to_challenge_group

Revision ID: 6c9c7266f920
Revises: 036d5c73a888
Create Date: 2025-05-26 15:37:41.986287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9c7266f920'
down_revision = '036d5c73a888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_penalty_duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penalty_applied_at_utc', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.drop_column('penalty_applied_at_utc')
        batch_op.drop_column('active_penalty_duration_seconds')

    # ### end Alembic commands ###
