"""Add SharedChallenge and ChallengeGroup models

Revision ID: a782c8316f6b
Revises: 
Create Date: 2025-03-31 16:25:09.308060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a782c8316f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # This drop index caused the first FK constraint error (1553)
    op.drop_index('ix_shared_challenges_creator_user_id', table_name='shared_challenges')

    # This create index likely caused a duplicate key error (1061) later
    op.create_index(op.f('ix_shared_challenges_creator_id'), 'shared_challenges', ['creator_id'], unique=False)

    # This create index is likely unnecessary (PK is usually indexed)
    op.create_index(op.f('ix_shared_challenges_id'), 'shared_challenges', ['id'], unique=False)

    # This drops the OLD foreign key (using potentially auto-generated name 'shared_challenges_ibfk_1')
    op.drop_constraint('shared_challenges_ibfk_1', 'shared_challenges', type_='foreignkey')

    # This drops an OLD column 'creator_user_id' - was this the original FK column name?
    op.drop_column('shared_challenges', 'creator_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_saved_game_tabs_user_id'), table_name='saved_game_tabs')
    op.drop_index(op.f('ix_saved_game_tabs_client_tab_id'), table_name='saved_game_tabs')
    op.drop_index(op.f('ix_game_entries_Spiel'), table_name='game_entries')
    op.drop_index('uq_challenge_group_name', table_name='challenge_groups')
    op.drop_index(op.f('ix_challenge_groups_shared_challenge_id'), table_name='challenge_groups')
    op.drop_table('challenge_groups')
    op.drop_index(op.f('ix_shared_challenges_public_id'), table_name='shared_challenges')
    op.drop_index(op.f('ix_shared_challenges_creator_user_id'), table_name='shared_challenges')
    op.drop_table('shared_challenges')
    # ### end Alembic commands ###
