"""pro plan added

Revision ID: ae4363f3c300
Revises: c334b9977631
Create Date: 2025-05-18 16:22:55.153840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4363f3c300'
down_revision = 'c334b9977631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pro_plan_active', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('pro_plan_expiration_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pro_plan_expiration_date')
        batch_op.drop_column('pro_plan_active')

    # ### end Alembic commands ###
