"""Reinitialize models with explicit M2M back_populates

Revision ID: c334b9977631
Revises: 
Create Date: 2025-05-14 16:02:44.896596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c334b9977631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Spiel', sa.String(length=100), nullable=False),
    sa.Column('Spielmodus', sa.String(length=100), nullable=False),
    sa.Column('Schwierigkeit', sa.Float(), nullable=False),
    sa.Column('Spieleranzahl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_entries_Spiel'), ['Spiel'], unique=False)

    op.create_table('penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('twitch_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('overlay_api_key', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_overlay_api_key'), ['overlay_api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_twitch_id'), ['twitch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('saved_game_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_tab_id', sa.String(length=100), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('entries_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_game_tabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_game_tabs_client_tab_id'), ['client_tab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_game_tabs_user_id'), ['user_id'], unique=False)

    op.create_table('saved_penalty_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_tab_id', sa.String(length=100), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('penalties_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_penalty_tabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_penalty_tabs_client_tab_id'), ['client_tab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_penalty_tabs_user_id'), ['user_id'], unique=False)

    op.create_table('shared_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('challenge_data', sa.JSON(), nullable=False),
    sa.Column('penalty_info', sa.JSON(), nullable=True),
    sa.Column('max_groups', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_players_per_group', sa.Integer(), server_default='1', nullable=False),
    sa.Column('timer_current_value_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timer_is_running', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('timer_last_started_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_challenges_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_challenges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_challenges_public_id'), ['public_id'], unique=True)

    op.create_table('challenge_authorized_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['shared_challenges.id'], name='fk_auth_challenge_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_auth_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id')
    )
    op.create_table('challenge_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_challenge_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_penalty_text', sa.String(length=255), nullable=True),
    sa.Column('player_names', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['shared_challenge_id'], ['shared_challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_groups_shared_challenge_id'), ['shared_challenge_id'], unique=False)
        batch_op.create_index('uq_shared_challenge_group_name', ['shared_challenge_id', 'group_name'], unique=True)

    op.create_table('user_challenge_group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['challenge_groups.id'], name='fk_membership_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_membership_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_challenge_group_membership')
    with op.batch_alter_table('challenge_groups', schema=None) as batch_op:
        batch_op.drop_index('uq_shared_challenge_group_name')
        batch_op.drop_index(batch_op.f('ix_challenge_groups_shared_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_groups_id'))

    op.drop_table('challenge_groups')
    op.drop_table('challenge_authorized_users')
    with op.batch_alter_table('shared_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_challenges_public_id'))
        batch_op.drop_index(batch_op.f('ix_shared_challenges_id'))
        batch_op.drop_index(batch_op.f('ix_shared_challenges_creator_id'))

    op.drop_table('shared_challenges')
    with op.batch_alter_table('saved_penalty_tabs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_penalty_tabs_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_penalty_tabs_client_tab_id'))

    op.drop_table('saved_penalty_tabs')
    with op.batch_alter_table('saved_game_tabs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_game_tabs_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_game_tabs_client_tab_id'))

    op.drop_table('saved_game_tabs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_twitch_id'))
        batch_op.drop_index(batch_op.f('ix_users_overlay_api_key'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('penalties')
    with op.batch_alter_table('game_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_entries_Spiel'))

    op.drop_table('game_entries')
    # ### end Alembic commands ###
